### PR TITLE
Add argument splitting logic

### PR DESCRIPTION
**Pull request by mcdado**
This solves the issue with spaces in printer names, and removes the expectation of invocation with quotes which are dealt with by Node's child_process.

### CODE REVIEW

**Comment by mcdado** [comment]
Closes https://github.com/artiebits/pdf-to-printer/issues/222.

**Comment by mcdado** [comment]
I tested on Windows, still need to test on macOS.

**Comment by mcdado** [comment]
Tested on unix as well, and solved conflicts with master.

**Comment by artiebits** [comment]
amazing work, David. thanks a lot!

**Pull request merged**
