### PR TITLE
observe method implementation

### LINKED ISSUE #251: Ability to get event when printing is done
Hi.

I need to know is my print job finished or not.
My solution is using `lpstat`  for monitoring the printing queue and emit an event when the job disappeared or failed
Is it implemented yet?
Thank you

### PR DESCRIPTION
**Pull request by gallyamow**
resolves #251

example: 

```
const jobId = await ptp.print("assets/pdf-sample.pdf")
const res = await ptp.observe(jobId, 60000, 1000)
console.log(res) 
```

### CODE REVIEW

**Comment by artiebits** [comment]
thank you very much for the contribution. let's resolve conflicts so I can merge it to master

**Comment by gallyamow** [comment]
> thank you very much for the contribution. let's resolve conflicts so I can merge it to master

Hi. I have no write access to this repository, so  the button "Resolve conflicts" is blocked for me.

**Comment by artiebits** [comment]
@gallyamow you should resolve conflicts on your laptop

**Comment by gallyamow** [comment]
> @gallyamow you should resolve conflicts on your laptop

Hi, done

**Comment by jsgeekes** [comment]
@artiebits when merged this merge request ?

thanks @gallyamow

**Comment by gallyamow** [comment]
> @artiebits when merged this merge request ?
> 
> thanks @gallyamow, its not work in windows ?

Hi, No it doesn't work in windows yet.

**Comment by artiebits** [comment]
hi guys, sorry for taking so long to merge the PR

**Comment by artiebits** [comment]
i've published a beta version ` 2.1.0-beta.1`, let me know if it works fine for you

**Pull request merged**
