### PR TITLE
remove validPaperSizes

### PR DESCRIPTION
**Pull request by demobiel**
Every printer can have different valid paper sizes, so I don't think we can hardcode them. 

Implementing a getter to retrieve valid papersizes for each platform by printername is out of the scope of this project.

### CODE REVIEW

**Comment by artiebits** [comment]
Hi @demobiel Thank you for your contribution, I appreciate it.

Did you test it? Will it work? I am asking because looks like SumatraPDF supports only page sizes mentioned in the docs https://www.sumatrapdfreader.org/docs/Command-line-arguments

**Comment by demobiel** [comment]
Good catch! 
We tried with an EPSON TM-C3500 with custom paper sizes and an Evolis Primacy PVC badgeprinter for CR80 cards on a Windows machine.

They printed fine, but I will ask to do some more testing (like: what happens if you provide an invalid paper size etc). Not sure if we use the native printer driver, or a CUPS server... so there might be a difference there.

**Review by angjelonuho — APPROVED** [review]

**Comment by artiebits** [comment]
Hi guys! Sorry for the delay, but I was on vacation. 

I've published a beta version `pdf-to-printer@5.3.0-beta.0` with your changes. Could you please check it and tell me if it works fine. I don't have a printer and windows machine to test it right now. If it works fine then I will merge it to master and release a new version ASAP.

**Comment by demobiel** [comment]
We will do the tests this week!

**Comment by artiebits** [comment]
@demobiel thank you!

**Pull request closed without merging**
