### PR TITLE
Change to SumatraPDF Version 3.0.0

### PR DESCRIPTION
**Pull request by BrunoGusChagas**

### CODE REVIEW

**Comment by artiebits** [comment]
Hi Bruno, 
thanks a lot for your contribution! I didn't have a chance to test it yet, but I've published a beta version `1.0.7-beta.0` with your changes. It would be nice if you test it as well. `npm i pdf-to-printer@1.0.7-beta.0`.

**Comment by artiebits** [comment]
Hi @BrunoGusChagas, sorry for the delay in response. 

One small question. The currently used version is 3.1.1. But I see that SumatraPDF has version 3.1 as well. Did you try it? Does it work for you?

**Comment by BrunoGusChagas** [comment]
> 
> 
> Hi @BrunoGusChagas, sorry for the delay in response.
> 
> One small question. The currently used version is 3.1.1. But I see that SumatraPDF has version 3.1 as well. Did you try it? Does it work for you?

Yes, I did try it @artiebits . Unfortunately the last version that works fine it is 3.0.0. It seams that after the version 3.0.0 they changed the way to convert files before printing , with this some problems started happening.

**Comment by artiebits** [comment]
@BrunoGusChagas ah, thanks. Could you help me to test `pdf-to-printer@1.0.7-beta.0` please? I don't have a Windows machine to do it anymore.

**Comment by BrunoGusChagas** [comment]
@artiebits sure ! I will try to test today and then give you some feedback !

**Comment by artiebits** [comment]
thanks a lot, Bruno!

**Comment by BrunoGusChagas** [comment]
Hi @artiebits ,I tested and it's working normally on Windows.

**Comment by artiebits** [comment]
Thank you Bruno, I've just merged your PR into master, will create a new release soon

**Pull request merged**
